### ISSUE TITLE
Grades export

### ISSUE THREAD

**Issue by RouNNdeL** [librus-stats/librus-stats-php#18]
Zaczne juz robic grafy na strone, wiec jakbys mi mogl dac jakąs mozliwosc latwgeo eksportu danych. Format csv, delimiter `;`. Kolumny takie: `grades.grade; categories.weight ;grades.date_added; grades.date; users.id; grades.semster; grades.subject`, np: `4+; 2; 2017-07-09T23:07:58; 2017-07-09 ;1337; 1; 36415`. Format daty daj jaki ci najwygodniej, ja sobie poradze

**Comment by Torisels** [comment]
Format daty standardowy z Mysql
 '1000-01-01 00:00:00'

**Comment by Torisels** [comment]
Zrobione. 
Skrypt jest w folderze server\dumps
Wykorzystanie: php dump.php <nazwa pliku do którego idzie dump>
(plik ten powinien utworzyć się w tym samym folderze).
W csv po każdym ';' następuje spacja.
Dodatkowo, w przypadku wartości null z bazy występuje 'NULL'

**Comment by RouNNdeL** [comment]
Jakbys mogl wywalic te spacje, dalem je tylko po to, zeby latwiej sie czytalo issue
