### ISSUE TITLE
Grade type column in dump

### ISSUE THREAD

**Issue by RouNNdeL** [librus-stats/librus-stats-php#21]
Dodaj kolumne z nazwa `grade_type` do dumpa ocen. Mozliwe wartosci:

- 0 - normalna ocena
- 1 - proponowana semstralna 
- 2 - semestralna 
- 3 - proponowana koncowa 
- 4 - koncowa

**Comment by RouNNdeL** [comment]
Btw jakbys zgubil nazwy poprzednich kolumn:
`grade;weight;date_added;date;term;subject;user;count2avg`

**Comment by Torisels** [comment]
php dump.php "path" "mode"

mode: "grades" || 'subjects"
